### ISSUE TITLE
AutoScroll autoScroll = (AutoScroll) mInnerAdapter;

### ISSUE THREAD

**Issue by scholar-yan** [wuyinlei/MarqueeView#1]
AutoScroll autoScroll = (AutoScroll) mInnerAdapter;，这里强转没有问题吗

**Comment by wuyinlei** [comment]
为啥有问题呢

**Comment by scholar-yan** [comment]
不会出现类型强转错误吗

**Comment by scholar-yan** [comment]
ClassCastException

**Comment by wuyinlei** [comment]
listView.setAdapter(new AutoScrollAdapter(mMarqueeBeen,this));

 AutoScrollAdapter extends BaseAdapter implements AutoScrollListView.AutoScroll

你看下这两行 ,会出现那个错误么？

**Comment by scholar-yan** [comment]
你看看AutoScrollListView.java这个类里面的mInnerAdapter这个变量是哪个类型的？InnerAdapter是不是AutoScrollAdapter 的子类，InnerAdapter继承BaseAdapter与AutoScroll什么关系

**Comment by scholar-yan** [comment]
给你看个链接：https://github.com/peerless2012/AutoScrollListView

**Comment by wuyinlei** [comment]
明白了 ， if (firstVisiblePosition == 0) {
//            AutoScroll autoScroll = (AutoScroll) mInnerAdapter;
//            targetPosition = mInnerAdapter.getCount() - autoScroll.getVisiableCount() * 2;
//        }
这一段代码不走,也就是说这段没用，也就是不会出现转换异常。。。。谢谢指正
